main page & article page
EduardKurbatov/NewYorkTimes pull request #10
Opened 2021-04-23 16:54 UTC by EduardKurbatov

2021-04-24 09:58 UTC, VeeShort requested changes
Пачка

2021-04-24 09:58 UTC, VeeShort commented on .vscode/launch.json
> +}
Мне кажется, что этот файл стоит добавить в `.gitignore`

2021-04-24 09:58 UTC, VeeShort commented on src/App.scss
> +}
Нет пустой строки

2021-04-24 09:58 UTC, VeeShort commented on src/App.scss
> +    padding: 0;
Табуляция

2021-04-24 09:58 UTC, VeeShort commented on src/App.tsx
> -            {/* If page is not found - redirect to Routes.MAIN */}
Зачем удалил этот коммент?

2021-04-24 09:58 UTC, VeeShort commented on src/App.tsx
> +import ArticlePage from './components/ArticlePage/ArticlePage';
Этот импорт лишний

2021-04-24 09:58 UTC, VeeShort commented on src/components/ArticlePage/ArticlePage.scss
> +        }
этот блок можно перенести выше под `.author`:
```css
.author {
  ...
  & > span {
    ...
  }
}

2021-04-24 09:58 UTC, VeeShort commented on src/components/ArticlePage/ArticlePage.scss
> +      margin-top: 10px;
Так как все-таки верно, `margin-top: 50px` или `margin-top: 10px`?

2021-04-24 09:58 UTC, VeeShort commented on src/components/ArticlePage/ArticlePage.scss
> +  and (max-device-width: 767px) {
Это все дело можно прописать в одну строку

2021-04-24 09:58 UTC, VeeShort commented on src/components/ArticlePage/ArticlePage.scss
> +  and (max-device-width: 1024px) {
Одной строкой плиз

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.scss
> +          margin-right: 15px;
не тот отступ

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.scss
> +    .article  {
лишний пробел перед скобкой

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.scss
> +  .articles-container{
Не хватает пробела перед скобкой

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.scss
> +      .article {
```css
.main-page  .articles-container .article {
```

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.tsx
> +    getArticles()
Наступит ли день когда ты перестанешь глотать точки с запятой, пробелы и другие знаки препинания?

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.tsx
> +              }
Слабо это в функцию засунуть?

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.tsx
> +      {!showArticle ?
Обычно знак вопроса переносят на новую строку

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.tsx
> +                  abstract: article.abstract
что-то мне подсказывает что есть смысл деструктурировать `article`

2021-04-24 09:58 UTC, VeeShort commented on src/components/Main/Main.tsx
> +      <ArticlePage articleItems={articleItems} setArticleItems={setArticleItems} setShowArticle={setShowArticle} />}
Почему компонента называется `ArticlePage`, а остальные не имеют в имени `Page`? Я бы убрал здесь `Page` и оставил просто `Article`. Не забудь везде это поменять

2021-04-24 09:58 UTC, VeeShort commented on src/components/Profile/Profile.tsx
> -      setUploadedImageName(file?.name); // checking if file is defined, because eslint wants it to be so
И зачем ты это удалил?

2021-04-24 09:58 UTC, VeeShort commented on src/components/Profile/Profile.tsx
> -        */
Зачем ты удаляешь комментарии? Пусть будут

2021-04-24 09:58 UTC, VeeShort commented on src/components/types.tsx
> +}
Забыл точку с запятой

2021-04-24 09:58 UTC, VeeShort commented on .vscode/launch.json
> +}
или вообще всю директорию `.vscode`

2021-04-24 09:58 UTC, VeeShort commented on src/components/ArticlePage/ArticlePage.scss
> +        }
Перенеси под `.author` как описано в одном из комментов выше

2021-04-24 09:58 UTC, VeeShort commented on src/components/ArticlePage/ArticlePage.tsx
> +    <div className='article-page'>
Одинарные кавычки

2021-04-24 10:12 UTC, VeeShort requested changes

2021-04-24 10:12 UTC, VeeShort commented on src/components/types.tsx
> +export type Items = {
Название типа очень абстрактное (на уровне "someType"), я бы переименовал это на что-то понятное, типа `ArticleItem`

2021-04-27 10:47 UTC, EduardKurbatov commented on .vscode/launch.json
> +}
директория .vscode уже состоит в файле  .gitignore

2021-04-27 12:28 UTC, EduardKurbatov commented
@VeeShort updated

2021-04-27 12:48 UTC, EduardKurbatov commented
@VeeShort update

2021-04-27 17:09 UTC, VeeShort requested changes
Парочка поверхностных комментов

2021-04-27 17:09 UTC, VeeShort commented on src/components/ArticleList/ArticleList.scss
> +}
Как-то не очень стилизировать разицу в 50px

2021-04-27 17:09 UTC, VeeShort commented on src/components/ArticleList/ArticleList.tsx
> +
Лишняя строка

2021-04-27 17:09 UTC, VeeShort commented on src/components/ArticleList/ArticleList.tsx
> +      {articles.map((article: ArticleItems, index) => {
`article` можно деструктурировать

2021-04-27 17:09 UTC, VeeShort commented on src/components/ArticleList/ArticleList.tsx
> +      }
Почему просто не передавать данные такие какие они есть?

2021-04-27 17:09 UTC, VeeShort commented on src/components/Main/Main.scss
>  }
Нет пустой строки в конце файла

2021-04-27 17:09 UTC, VeeShort commented on src/components/Main/Main.tsx
> +          <Article articleItems={articleItems} setArticleItems={setArticleItems} setShowArticle={setShowArticle} />}
```jsx
{!showArtcile
  ? <ArticleList user={user} articles={articles} setArticleItems={setArticleItems} setShowArticle={setShowArticle} />
  : <Article articleItems={articleItems} setArticleItems={setArticleItems} setShowArticle={setShowArticle} />
}
```

2021-04-27 17:09 UTC, VeeShort commented on src/components/Profile/Profile.tsx
>          */
Комментарий должен быть перед `const user`, будь внимательнее или хотя бы смотри историю изменений чтобы вернуть на то же место

2021-04-27 17:09 UTC, VeeShort commented on src/components/types.tsx
> +export type ArticleItems = {
Почему название типа данных который репрезентит один элемент, описано в множественном числе? Я бы переименовал на `ArticleRecord`

2021-04-27 17:09 UTC, VeeShort commented on src/components/types.tsx
> +};
А этот тип я бы убрал совсем т.к. у нас уже есть тип выше (будущий `ArticleRecord`)

2021-04-27 17:45 UTC, EduardKurbatov commented
@VeeShort updated

2021-04-30 11:29 UTC, VeeShort requested changes
Code style

2021-04-30 11:29 UTC, VeeShort commented on src/App.tsx
> +
Лишняя пустая строка

2021-04-30 11:29 UTC, VeeShort commented on src/components/Profile/Profile.tsx
> +          * updateProfile method gets removed from the User object for some reason
Лишний пробел перед `*`

2021-04-30 11:29 UTC, VeeShort commented on src/components/Profile/Profile.tsx
> +
Лишняя строка

2021-04-30 11:29 UTC, VeeShort commented on src/components/Main/Main.tsx
> +        : <Article articleItems={articleItems} setArticleItems={setArticleItems} setShowArticle={setShowArticle} />}
Перенеси фигурную скобку на новую строку

2021-04-30 11:29 UTC, VeeShort commented on src/components/Main/Main.tsx
>      <div className="main-page">
```jsx
  ? <h2>loading...</h2>
  : <div className="main-page">
```

2021-04-30 11:51 UTC, VeeShort requested changes
Еще парочка

2021-04-30 11:51 UTC, VeeShort commented on src/components/Article/Article.tsx
> +  articleItems: ArticleRecord | undefined,
Желательно переименовать на `articleRecords` или `articles`

2021-04-30 11:51 UTC, VeeShort commented on src/components/Article/Article.tsx
> +    setShowArticle(false);
Этот стейт не нужен, можно тоглить проверяя значение `articleRecords`

2021-04-30 11:51 UTC, VeeShort commented on src/components/ArticleList/ArticleList.tsx
> +        )})}
Надо выровнять и перенести скобки

2021-04-30 11:51 UTC, VeeShort commented on src/components/Main/Main.tsx
> +      setLoading(false);
Нужно перенести `setLoader` **после** `else`

2021-04-30 11:51 UTC, VeeShort commented on src/components/Main/Main.tsx
>      };
Лишняя `;`

2021-04-30 13:43 UTC, EduardKurbatov commented
@VeeShort updated

2021-04-30 13:52 UTC, VeeShort requested changes
Парочка

2021-04-30 13:52 UTC, VeeShort commented on src/App.scss
> -
Нужна пустая строка в конце файла

2021-04-30 13:52 UTC, VeeShort commented on src/components/Article/Article.tsx
> +      {articleRecords?.media && <img className="article-image" src={articleRecords?.media[0]['media-metadata'][2].url} />}
`src={articleRecords?` здесь уже не нужно проверять наличие поля `media` т.к. ты это сделал в начале этой строки

2021-04-30 13:52 UTC, VeeShort commented on src/components/Main/Main.tsx
> +    setLoading(false);
Нужна пустая строка перед `setLoading`

2021-04-30 13:52 UTC, VeeShort commented on src/components/Main/Main.tsx
>      </div>
Увеличь отступ на 2 пробела

2021-04-30 14:05 UTC, EduardKurbatov commented
@VeeShort updated

2021-11-29 16:36 UTC, VeeShort approved these changes
lgtm :heavy_check_mark:

2022-01-27 17:05 UTC, merged